---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-0

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-0
  labels:
    workspace: workspace-0
spec:
  importedConfig:
    kubeConfigSecret: simulator-0-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-1

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-1
  labels:
    workspace: workspace-1
spec:
  importedConfig:
    kubeConfigSecret: simulator-1-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-2

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-2
  labels:
    workspace: workspace-2
spec:
  importedConfig:
    kubeConfigSecret: simulator-2-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-3

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-3
  labels:
    workspace: workspace-3
spec:
  importedConfig:
    kubeConfigSecret: simulator-3-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-4

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-4
  labels:
    workspace: workspace-4
spec:
  importedConfig:
    kubeConfigSecret: simulator-4-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-5

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-5
  labels:
    workspace: workspace-5
spec:
  importedConfig:
    kubeConfigSecret: simulator-5-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-6

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-6
  labels:
    workspace: workspace-6
spec:
  importedConfig:
    kubeConfigSecret: simulator-6-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-7

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-7
  labels:
    workspace: workspace-7
spec:
  importedConfig:
    kubeConfigSecret: simulator-7-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-8

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-8
  labels:
    workspace: workspace-8
spec:
  importedConfig:
    kubeConfigSecret: simulator-8-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-9

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-9
  labels:
    workspace: workspace-9
spec:
  importedConfig:
    kubeConfigSecret: simulator-9-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-10

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-10
  labels:
    workspace: workspace-10
spec:
  importedConfig:
    kubeConfigSecret: simulator-10-kubeconfig
