---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-1
  namespace: fleet-default

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-1
  namespace: fleet-default
  labels:
    workspace: workspace-1
spec:
  importedConfig:
    kubeConfigSecret: simulator-1-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-2
  namespace: fleet-default

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-2
  namespace: fleet-default
  labels:
    workspace: workspace-2
spec:
  importedConfig:
    kubeConfigSecret: simulator-2-kubeconfig
