---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-00001-1
  namespace: fleet-default

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-00001-1
  namespace: fleet-default
  labels:
    workspace: "workspace-00001"
    count: "1"
spec:
  importedConfig:
    kubeConfigSecret: simulator-00001-1-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-00001-2
  namespace: fleet-default

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-00001-2
  namespace: fleet-default
  labels:
    workspace: "workspace-00001"
    count: "2"
spec:
  importedConfig:
    kubeConfigSecret: simulator-00001-2-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-00002-1
  namespace: fleet-default

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-00002-1
  namespace: fleet-default
  labels:
    workspace: "workspace-00002"
    count: "1"
spec:
  importedConfig:
    kubeConfigSecret: simulator-00002-1-kubeconfig
---
kind: K3s
apiVersion: k3s.ibtc.io/v1
metadata:
  name: simulator-00002-2
  namespace: fleet-default

---
kind: Cluster
apiVersion: rancher.cattle.io/v1
metadata:
  name: simulator-00002-2
  namespace: fleet-default
  labels:
    workspace: "workspace-00002"
    count: "2"
spec:
  importedConfig:
    kubeConfigSecret: simulator-00002-2-kubeconfig
